// Code generated by mockery v2.53.5. DO NOT EDIT.

package product

import (
	context "context"

	activate_product "github.com/dawitel/catalog-proj/internal/app/product/usecases/activate_product"

	mock "github.com/stretchr/testify/mock"
)

// MockActivateRunner is an autogenerated mock type for the ActivateRunner type
type MockActivateRunner struct {
	mock.Mock
}

type MockActivateRunner_Expecter struct {
	mock *mock.Mock
}

func (_m *MockActivateRunner) EXPECT() *MockActivateRunner_Expecter {
	return &MockActivateRunner_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: ctx, req
func (_m *MockActivateRunner) Execute(ctx context.Context, req activate_product.Request) error {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, activate_product.Request) error); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockActivateRunner_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockActivateRunner_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
//   - req activate_product.Request
func (_e *MockActivateRunner_Expecter) Execute(ctx interface{}, req interface{}) *MockActivateRunner_Execute_Call {
	return &MockActivateRunner_Execute_Call{Call: _e.mock.On("Execute", ctx, req)}
}

func (_c *MockActivateRunner_Execute_Call) Run(run func(ctx context.Context, req activate_product.Request)) *MockActivateRunner_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(activate_product.Request))
	})
	return _c
}

func (_c *MockActivateRunner_Execute_Call) Return(_a0 error) *MockActivateRunner_Execute_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockActivateRunner_Execute_Call) RunAndReturn(run func(context.Context, activate_product.Request) error) *MockActivateRunner_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockActivateRunner creates a new instance of MockActivateRunner. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockActivateRunner(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockActivateRunner {
	mock := &MockActivateRunner{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
