// Code generated by mockery v2.53.5. DO NOT EDIT.

package product

import (
	context "context"

	deactivate_product "github.com/dawitel/catalog-proj/internal/app/product/usecases/deactivate_product"
	mock "github.com/stretchr/testify/mock"
)

// MockDeactivateRunner is an autogenerated mock type for the DeactivateRunner type
type MockDeactivateRunner struct {
	mock.Mock
}

type MockDeactivateRunner_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDeactivateRunner) EXPECT() *MockDeactivateRunner_Expecter {
	return &MockDeactivateRunner_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: ctx, req
func (_m *MockDeactivateRunner) Execute(ctx context.Context, req deactivate_product.Request) error {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, deactivate_product.Request) error); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockDeactivateRunner_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockDeactivateRunner_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
//   - req deactivate_product.Request
func (_e *MockDeactivateRunner_Expecter) Execute(ctx interface{}, req interface{}) *MockDeactivateRunner_Execute_Call {
	return &MockDeactivateRunner_Execute_Call{Call: _e.mock.On("Execute", ctx, req)}
}

func (_c *MockDeactivateRunner_Execute_Call) Run(run func(ctx context.Context, req deactivate_product.Request)) *MockDeactivateRunner_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(deactivate_product.Request))
	})
	return _c
}

func (_c *MockDeactivateRunner_Execute_Call) Return(_a0 error) *MockDeactivateRunner_Execute_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockDeactivateRunner_Execute_Call) RunAndReturn(run func(context.Context, deactivate_product.Request) error) *MockDeactivateRunner_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockDeactivateRunner creates a new instance of MockDeactivateRunner. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDeactivateRunner(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDeactivateRunner {
	mock := &MockDeactivateRunner{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
