// Code generated by mockery v2.53.5. DO NOT EDIT.

package product

import (
	context "context"

	contracts "github.com/dawitel/product-catalog-service/internal/app/product/contracts"
	list_products "github.com/dawitel/product-catalog-service/internal/app/product/queries/list_products"

	mock "github.com/stretchr/testify/mock"
)

// MockListProductsRunner is an autogenerated mock type for the ListProductsRunner type
type MockListProductsRunner struct {
	mock.Mock
}

type MockListProductsRunner_Expecter struct {
	mock *mock.Mock
}

func (_m *MockListProductsRunner) EXPECT() *MockListProductsRunner_Expecter {
	return &MockListProductsRunner_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: ctx, filter, page
func (_m *MockListProductsRunner) Execute(ctx context.Context, filter contracts.ListFilter, page contracts.ListPage) (*list_products.Result, error) {
	ret := _m.Called(ctx, filter, page)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 *list_products.Result
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, contracts.ListFilter, contracts.ListPage) (*list_products.Result, error)); ok {
		return rf(ctx, filter, page)
	}
	if rf, ok := ret.Get(0).(func(context.Context, contracts.ListFilter, contracts.ListPage) *list_products.Result); ok {
		r0 = rf(ctx, filter, page)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*list_products.Result)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, contracts.ListFilter, contracts.ListPage) error); ok {
		r1 = rf(ctx, filter, page)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockListProductsRunner_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockListProductsRunner_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
//   - filter contracts.ListFilter
//   - page contracts.ListPage
func (_e *MockListProductsRunner_Expecter) Execute(ctx interface{}, filter interface{}, page interface{}) *MockListProductsRunner_Execute_Call {
	return &MockListProductsRunner_Execute_Call{Call: _e.mock.On("Execute", ctx, filter, page)}
}

func (_c *MockListProductsRunner_Execute_Call) Run(run func(ctx context.Context, filter contracts.ListFilter, page contracts.ListPage)) *MockListProductsRunner_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(contracts.ListFilter), args[2].(contracts.ListPage))
	})
	return _c
}

func (_c *MockListProductsRunner_Execute_Call) Return(_a0 *list_products.Result, _a1 error) *MockListProductsRunner_Execute_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockListProductsRunner_Execute_Call) RunAndReturn(run func(context.Context, contracts.ListFilter, contracts.ListPage) (*list_products.Result, error)) *MockListProductsRunner_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockListProductsRunner creates a new instance of MockListProductsRunner. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockListProductsRunner(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockListProductsRunner {
	mock := &MockListProductsRunner{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
