// Code generated by mockery v2.53.5. DO NOT EDIT.

package product

import (
	context "context"

	archive_product "github.com/dawitel/product-catalog-service/internal/app/product/usecases/archive_product"

	mock "github.com/stretchr/testify/mock"
)

// MockArchiveRunner is an autogenerated mock type for the ArchiveRunner type
type MockArchiveRunner struct {
	mock.Mock
}

type MockArchiveRunner_Expecter struct {
	mock *mock.Mock
}

func (_m *MockArchiveRunner) EXPECT() *MockArchiveRunner_Expecter {
	return &MockArchiveRunner_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: ctx, req
func (_m *MockArchiveRunner) Execute(ctx context.Context, req archive_product.Request) error {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, archive_product.Request) error); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockArchiveRunner_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockArchiveRunner_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
//   - req archive_product.Request
func (_e *MockArchiveRunner_Expecter) Execute(ctx interface{}, req interface{}) *MockArchiveRunner_Execute_Call {
	return &MockArchiveRunner_Execute_Call{Call: _e.mock.On("Execute", ctx, req)}
}

func (_c *MockArchiveRunner_Execute_Call) Run(run func(ctx context.Context, req archive_product.Request)) *MockArchiveRunner_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(archive_product.Request))
	})
	return _c
}

func (_c *MockArchiveRunner_Execute_Call) Return(_a0 error) *MockArchiveRunner_Execute_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockArchiveRunner_Execute_Call) RunAndReturn(run func(context.Context, archive_product.Request) error) *MockArchiveRunner_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockArchiveRunner creates a new instance of MockArchiveRunner. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockArchiveRunner(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockArchiveRunner {
	mock := &MockArchiveRunner{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
