// Code generated by mockery v2.53.5. DO NOT EDIT.

package product

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	remove_discount "github.com/dawitel/product-catalog-service/internal/app/product/usecases/remove_discount"
)

// MockRemoveDiscountRunner is an autogenerated mock type for the RemoveDiscountRunner type
type MockRemoveDiscountRunner struct {
	mock.Mock
}

type MockRemoveDiscountRunner_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRemoveDiscountRunner) EXPECT() *MockRemoveDiscountRunner_Expecter {
	return &MockRemoveDiscountRunner_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: ctx, req
func (_m *MockRemoveDiscountRunner) Execute(ctx context.Context, req remove_discount.Request) error {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, remove_discount.Request) error); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRemoveDiscountRunner_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockRemoveDiscountRunner_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
//   - req remove_discount.Request
func (_e *MockRemoveDiscountRunner_Expecter) Execute(ctx interface{}, req interface{}) *MockRemoveDiscountRunner_Execute_Call {
	return &MockRemoveDiscountRunner_Execute_Call{Call: _e.mock.On("Execute", ctx, req)}
}

func (_c *MockRemoveDiscountRunner_Execute_Call) Run(run func(ctx context.Context, req remove_discount.Request)) *MockRemoveDiscountRunner_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(remove_discount.Request))
	})
	return _c
}

func (_c *MockRemoveDiscountRunner_Execute_Call) Return(_a0 error) *MockRemoveDiscountRunner_Execute_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRemoveDiscountRunner_Execute_Call) RunAndReturn(run func(context.Context, remove_discount.Request) error) *MockRemoveDiscountRunner_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRemoveDiscountRunner creates a new instance of MockRemoveDiscountRunner. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRemoveDiscountRunner(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRemoveDiscountRunner {
	mock := &MockRemoveDiscountRunner{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
