// Code generated by mockery v2.53.5. DO NOT EDIT.

package product

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	update_product "github.com/dawitel/catalog-proj/internal/app/product/usecases/update_product"
)

// MockUpdateRunner is an autogenerated mock type for the UpdateRunner type
type MockUpdateRunner struct {
	mock.Mock
}

type MockUpdateRunner_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUpdateRunner) EXPECT() *MockUpdateRunner_Expecter {
	return &MockUpdateRunner_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: ctx, req
func (_m *MockUpdateRunner) Execute(ctx context.Context, req update_product.Request) error {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, update_product.Request) error); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockUpdateRunner_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockUpdateRunner_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
//   - req update_product.Request
func (_e *MockUpdateRunner_Expecter) Execute(ctx interface{}, req interface{}) *MockUpdateRunner_Execute_Call {
	return &MockUpdateRunner_Execute_Call{Call: _e.mock.On("Execute", ctx, req)}
}

func (_c *MockUpdateRunner_Execute_Call) Run(run func(ctx context.Context, req update_product.Request)) *MockUpdateRunner_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(update_product.Request))
	})
	return _c
}

func (_c *MockUpdateRunner_Execute_Call) Return(_a0 error) *MockUpdateRunner_Execute_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUpdateRunner_Execute_Call) RunAndReturn(run func(context.Context, update_product.Request) error) *MockUpdateRunner_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUpdateRunner creates a new instance of MockUpdateRunner. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUpdateRunner(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUpdateRunner {
	mock := &MockUpdateRunner{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
