// Code generated by mockery v2.53.5. DO NOT EDIT.

package product

import (
	context "context"

	get_product "github.com/dawitel/catalog-proj/internal/app/product/queries/get_product"
	mock "github.com/stretchr/testify/mock"
)

// MockGetProductRunner is an autogenerated mock type for the GetProductRunner type
type MockGetProductRunner struct {
	mock.Mock
}

type MockGetProductRunner_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGetProductRunner) EXPECT() *MockGetProductRunner_Expecter {
	return &MockGetProductRunner_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: ctx, productID
func (_m *MockGetProductRunner) Execute(ctx context.Context, productID string) (*get_product.DTO, error) {
	ret := _m.Called(ctx, productID)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 *get_product.DTO
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*get_product.DTO, error)); ok {
		return rf(ctx, productID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *get_product.DTO); ok {
		r0 = rf(ctx, productID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*get_product.DTO)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, productID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockGetProductRunner_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockGetProductRunner_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
//   - productID string
func (_e *MockGetProductRunner_Expecter) Execute(ctx interface{}, productID interface{}) *MockGetProductRunner_Execute_Call {
	return &MockGetProductRunner_Execute_Call{Call: _e.mock.On("Execute", ctx, productID)}
}

func (_c *MockGetProductRunner_Execute_Call) Run(run func(ctx context.Context, productID string)) *MockGetProductRunner_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockGetProductRunner_Execute_Call) Return(_a0 *get_product.DTO, _a1 error) *MockGetProductRunner_Execute_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockGetProductRunner_Execute_Call) RunAndReturn(run func(context.Context, string) (*get_product.DTO, error)) *MockGetProductRunner_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockGetProductRunner creates a new instance of MockGetProductRunner. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGetProductRunner(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGetProductRunner {
	mock := &MockGetProductRunner{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
