// Code generated by mockery v2.53.5. DO NOT EDIT.

package product

import (
	context "context"

	create_product "github.com/dawitel/catalog-proj/internal/app/product/usecases/create_product"
	mock "github.com/stretchr/testify/mock"
)

// MockCreateRunner is an autogenerated mock type for the CreateRunner type
type MockCreateRunner struct {
	mock.Mock
}

type MockCreateRunner_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCreateRunner) EXPECT() *MockCreateRunner_Expecter {
	return &MockCreateRunner_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: ctx, req
func (_m *MockCreateRunner) Execute(ctx context.Context, req create_product.Request) (string, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, create_product.Request) (string, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, create_product.Request) string); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, create_product.Request) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCreateRunner_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockCreateRunner_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
//   - req create_product.Request
func (_e *MockCreateRunner_Expecter) Execute(ctx interface{}, req interface{}) *MockCreateRunner_Execute_Call {
	return &MockCreateRunner_Execute_Call{Call: _e.mock.On("Execute", ctx, req)}
}

func (_c *MockCreateRunner_Execute_Call) Run(run func(ctx context.Context, req create_product.Request)) *MockCreateRunner_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(create_product.Request))
	})
	return _c
}

func (_c *MockCreateRunner_Execute_Call) Return(_a0 string, _a1 error) *MockCreateRunner_Execute_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCreateRunner_Execute_Call) RunAndReturn(run func(context.Context, create_product.Request) (string, error)) *MockCreateRunner_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockCreateRunner creates a new instance of MockCreateRunner. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCreateRunner(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCreateRunner {
	mock := &MockCreateRunner{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
