// Code generated by mockery v2.53.5. DO NOT EDIT.

package product

import (
	context "context"

	apply_discount "github.com/dawitel/catalog-proj/internal/app/product/usecases/apply_discount"

	mock "github.com/stretchr/testify/mock"
)

// MockApplyDiscountRunner is an autogenerated mock type for the ApplyDiscountRunner type
type MockApplyDiscountRunner struct {
	mock.Mock
}

type MockApplyDiscountRunner_Expecter struct {
	mock *mock.Mock
}

func (_m *MockApplyDiscountRunner) EXPECT() *MockApplyDiscountRunner_Expecter {
	return &MockApplyDiscountRunner_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: ctx, req
func (_m *MockApplyDiscountRunner) Execute(ctx context.Context, req apply_discount.Request) error {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, apply_discount.Request) error); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockApplyDiscountRunner_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockApplyDiscountRunner_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
//   - req apply_discount.Request
func (_e *MockApplyDiscountRunner_Expecter) Execute(ctx interface{}, req interface{}) *MockApplyDiscountRunner_Execute_Call {
	return &MockApplyDiscountRunner_Execute_Call{Call: _e.mock.On("Execute", ctx, req)}
}

func (_c *MockApplyDiscountRunner_Execute_Call) Run(run func(ctx context.Context, req apply_discount.Request)) *MockApplyDiscountRunner_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(apply_discount.Request))
	})
	return _c
}

func (_c *MockApplyDiscountRunner_Execute_Call) Return(_a0 error) *MockApplyDiscountRunner_Execute_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockApplyDiscountRunner_Execute_Call) RunAndReturn(run func(context.Context, apply_discount.Request) error) *MockApplyDiscountRunner_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockApplyDiscountRunner creates a new instance of MockApplyDiscountRunner. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockApplyDiscountRunner(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockApplyDiscountRunner {
	mock := &MockApplyDiscountRunner{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
