// Code generated by mockery v2.53.5. DO NOT EDIT.

package contracts

import (
	spanner "cloud.google.com/go/spanner"
	mock "github.com/stretchr/testify/mock"

	time "time"
)

// MockOutboxRepo is an autogenerated mock type for the OutboxRepo type
type MockOutboxRepo struct {
	mock.Mock
}

type MockOutboxRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOutboxRepo) EXPECT() *MockOutboxRepo_Expecter {
	return &MockOutboxRepo_Expecter{mock: &_m.Mock}
}

// InsertMut provides a mock function with given fields: eventID, eventType, aggregateID, payload, status, createdAt
func (_m *MockOutboxRepo) InsertMut(eventID string, eventType string, aggregateID string, payload string, status string, createdAt time.Time) *spanner.Mutation {
	ret := _m.Called(eventID, eventType, aggregateID, payload, status, createdAt)

	if len(ret) == 0 {
		panic("no return value specified for InsertMut")
	}

	var r0 *spanner.Mutation
	if rf, ok := ret.Get(0).(func(string, string, string, string, string, time.Time) *spanner.Mutation); ok {
		r0 = rf(eventID, eventType, aggregateID, payload, status, createdAt)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*spanner.Mutation)
		}
	}

	return r0
}

// MockOutboxRepo_InsertMut_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InsertMut'
type MockOutboxRepo_InsertMut_Call struct {
	*mock.Call
}

// InsertMut is a helper method to define mock.On call
//   - eventID string
//   - eventType string
//   - aggregateID string
//   - payload string
//   - status string
//   - createdAt time.Time
func (_e *MockOutboxRepo_Expecter) InsertMut(eventID interface{}, eventType interface{}, aggregateID interface{}, payload interface{}, status interface{}, createdAt interface{}) *MockOutboxRepo_InsertMut_Call {
	return &MockOutboxRepo_InsertMut_Call{Call: _e.mock.On("InsertMut", eventID, eventType, aggregateID, payload, status, createdAt)}
}

func (_c *MockOutboxRepo_InsertMut_Call) Run(run func(eventID string, eventType string, aggregateID string, payload string, status string, createdAt time.Time)) *MockOutboxRepo_InsertMut_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string), args[2].(string), args[3].(string), args[4].(string), args[5].(time.Time))
	})
	return _c
}

func (_c *MockOutboxRepo_InsertMut_Call) Return(_a0 *spanner.Mutation) *MockOutboxRepo_InsertMut_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockOutboxRepo_InsertMut_Call) RunAndReturn(run func(string, string, string, string, string, time.Time) *spanner.Mutation) *MockOutboxRepo_InsertMut_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockOutboxRepo creates a new instance of MockOutboxRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOutboxRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOutboxRepo {
	mock := &MockOutboxRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
