// Code generated by mockery v2.53.5. DO NOT EDIT.

package contracts

import (
	context "context"

	contracts "github.com/dawitel/product-catalog-service/internal/app/product/contracts"
	mock "github.com/stretchr/testify/mock"
)

// MockReadModel is an autogenerated mock type for the ReadModel type
type MockReadModel struct {
	mock.Mock
}

type MockReadModel_Expecter struct {
	mock *mock.Mock
}

func (_m *MockReadModel) EXPECT() *MockReadModel_Expecter {
	return &MockReadModel_Expecter{mock: &_m.Mock}
}

// GetProductByID provides a mock function with given fields: ctx, id
func (_m *MockReadModel) GetProductByID(ctx context.Context, id string) (*contracts.ProductRow, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetProductByID")
	}

	var r0 *contracts.ProductRow
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*contracts.ProductRow, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *contracts.ProductRow); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*contracts.ProductRow)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockReadModel_GetProductByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetProductByID'
type MockReadModel_GetProductByID_Call struct {
	*mock.Call
}

// GetProductByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockReadModel_Expecter) GetProductByID(ctx interface{}, id interface{}) *MockReadModel_GetProductByID_Call {
	return &MockReadModel_GetProductByID_Call{Call: _e.mock.On("GetProductByID", ctx, id)}
}

func (_c *MockReadModel_GetProductByID_Call) Run(run func(ctx context.Context, id string)) *MockReadModel_GetProductByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockReadModel_GetProductByID_Call) Return(_a0 *contracts.ProductRow, _a1 error) *MockReadModel_GetProductByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockReadModel_GetProductByID_Call) RunAndReturn(run func(context.Context, string) (*contracts.ProductRow, error)) *MockReadModel_GetProductByID_Call {
	_c.Call.Return(run)
	return _c
}

// ListProducts provides a mock function with given fields: ctx, filter, page
func (_m *MockReadModel) ListProducts(ctx context.Context, filter contracts.ListFilter, page contracts.ListPage) (*contracts.ListProductsResult, error) {
	ret := _m.Called(ctx, filter, page)

	if len(ret) == 0 {
		panic("no return value specified for ListProducts")
	}

	var r0 *contracts.ListProductsResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, contracts.ListFilter, contracts.ListPage) (*contracts.ListProductsResult, error)); ok {
		return rf(ctx, filter, page)
	}
	if rf, ok := ret.Get(0).(func(context.Context, contracts.ListFilter, contracts.ListPage) *contracts.ListProductsResult); ok {
		r0 = rf(ctx, filter, page)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*contracts.ListProductsResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, contracts.ListFilter, contracts.ListPage) error); ok {
		r1 = rf(ctx, filter, page)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockReadModel_ListProducts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListProducts'
type MockReadModel_ListProducts_Call struct {
	*mock.Call
}

// ListProducts is a helper method to define mock.On call
//   - ctx context.Context
//   - filter contracts.ListFilter
//   - page contracts.ListPage
func (_e *MockReadModel_Expecter) ListProducts(ctx interface{}, filter interface{}, page interface{}) *MockReadModel_ListProducts_Call {
	return &MockReadModel_ListProducts_Call{Call: _e.mock.On("ListProducts", ctx, filter, page)}
}

func (_c *MockReadModel_ListProducts_Call) Run(run func(ctx context.Context, filter contracts.ListFilter, page contracts.ListPage)) *MockReadModel_ListProducts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(contracts.ListFilter), args[2].(contracts.ListPage))
	})
	return _c
}

func (_c *MockReadModel_ListProducts_Call) Return(_a0 *contracts.ListProductsResult, _a1 error) *MockReadModel_ListProducts_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockReadModel_ListProducts_Call) RunAndReturn(run func(context.Context, contracts.ListFilter, contracts.ListPage) (*contracts.ListProductsResult, error)) *MockReadModel_ListProducts_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockReadModel creates a new instance of MockReadModel. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockReadModel(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockReadModel {
	mock := &MockReadModel{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
