// Code generated by mockery v2.53.5. DO NOT EDIT.

package contracts

import (
	context "context"

	commitplan "github.com/dawitel/product-catalog-service/internal/commitplan"

	domain "github.com/dawitel/product-catalog-service/internal/app/product/domain"

	mock "github.com/stretchr/testify/mock"

	spanner "cloud.google.com/go/spanner"
)

// MockProductRepo is an autogenerated mock type for the ProductRepo type
type MockProductRepo struct {
	mock.Mock
}

type MockProductRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *MockProductRepo) EXPECT() *MockProductRepo_Expecter {
	return &MockProductRepo_Expecter{mock: &_m.Mock}
}

// Get provides a mock function with given fields: ctx, id
func (_m *MockProductRepo) Get(ctx context.Context, id string) (*domain.Product, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *domain.Product
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.Product, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.Product); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Product)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockProductRepo_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockProductRepo_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockProductRepo_Expecter) Get(ctx interface{}, id interface{}) *MockProductRepo_Get_Call {
	return &MockProductRepo_Get_Call{Call: _e.mock.On("Get", ctx, id)}
}

func (_c *MockProductRepo_Get_Call) Run(run func(ctx context.Context, id string)) *MockProductRepo_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockProductRepo_Get_Call) Return(_a0 *domain.Product, _a1 error) *MockProductRepo_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockProductRepo_Get_Call) RunAndReturn(run func(context.Context, string) (*domain.Product, error)) *MockProductRepo_Get_Call {
	_c.Call.Return(run)
	return _c
}

// InsertMut provides a mock function with given fields: p
func (_m *MockProductRepo) InsertMut(p *domain.Product) *spanner.Mutation {
	ret := _m.Called(p)

	if len(ret) == 0 {
		panic("no return value specified for InsertMut")
	}

	var r0 *spanner.Mutation
	if rf, ok := ret.Get(0).(func(*domain.Product) *spanner.Mutation); ok {
		r0 = rf(p)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*spanner.Mutation)
		}
	}

	return r0
}

// MockProductRepo_InsertMut_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InsertMut'
type MockProductRepo_InsertMut_Call struct {
	*mock.Call
}

// InsertMut is a helper method to define mock.On call
//   - p *domain.Product
func (_e *MockProductRepo_Expecter) InsertMut(p interface{}) *MockProductRepo_InsertMut_Call {
	return &MockProductRepo_InsertMut_Call{Call: _e.mock.On("InsertMut", p)}
}

func (_c *MockProductRepo_InsertMut_Call) Run(run func(p *domain.Product)) *MockProductRepo_InsertMut_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*domain.Product))
	})
	return _c
}

func (_c *MockProductRepo_InsertMut_Call) Return(_a0 *spanner.Mutation) *MockProductRepo_InsertMut_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockProductRepo_InsertMut_Call) RunAndReturn(run func(*domain.Product) *spanner.Mutation) *MockProductRepo_InsertMut_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateConditional provides a mock function with given fields: p
func (_m *MockProductRepo) UpdateConditional(p *domain.Product) *commitplan.ConditionalUpdate {
	ret := _m.Called(p)

	if len(ret) == 0 {
		panic("no return value specified for UpdateConditional")
	}

	var r0 *commitplan.ConditionalUpdate
	if rf, ok := ret.Get(0).(func(*domain.Product) *commitplan.ConditionalUpdate); ok {
		r0 = rf(p)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*commitplan.ConditionalUpdate)
		}
	}

	return r0
}

// MockProductRepo_UpdateConditional_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateConditional'
type MockProductRepo_UpdateConditional_Call struct {
	*mock.Call
}

// UpdateConditional is a helper method to define mock.On call
//   - p *domain.Product
func (_e *MockProductRepo_Expecter) UpdateConditional(p interface{}) *MockProductRepo_UpdateConditional_Call {
	return &MockProductRepo_UpdateConditional_Call{Call: _e.mock.On("UpdateConditional", p)}
}

func (_c *MockProductRepo_UpdateConditional_Call) Run(run func(p *domain.Product)) *MockProductRepo_UpdateConditional_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*domain.Product))
	})
	return _c
}

func (_c *MockProductRepo_UpdateConditional_Call) Return(_a0 *commitplan.ConditionalUpdate) *MockProductRepo_UpdateConditional_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockProductRepo_UpdateConditional_Call) RunAndReturn(run func(*domain.Product) *commitplan.ConditionalUpdate) *MockProductRepo_UpdateConditional_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockProductRepo creates a new instance of MockProductRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockProductRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockProductRepo {
	mock := &MockProductRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
