// Code generated by mockery v2.53.5. DO NOT EDIT.

package commitplan

import (
	context "context"

	commitplan "github.com/dawitel/product-catalog-service/internal/commitplan"

	mock "github.com/stretchr/testify/mock"
)

// MockApplier is an autogenerated mock type for the Applier type
type MockApplier struct {
	mock.Mock
}

type MockApplier_Expecter struct {
	mock *mock.Mock
}

func (_m *MockApplier) EXPECT() *MockApplier_Expecter {
	return &MockApplier_Expecter{mock: &_m.Mock}
}

// Apply provides a mock function with given fields: ctx, plan
func (_m *MockApplier) Apply(ctx context.Context, plan *commitplan.Plan) error {
	ret := _m.Called(ctx, plan)

	if len(ret) == 0 {
		panic("no return value specified for Apply")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *commitplan.Plan) error); ok {
		r0 = rf(ctx, plan)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockApplier_Apply_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Apply'
type MockApplier_Apply_Call struct {
	*mock.Call
}

// Apply is a helper method to define mock.On call
//   - ctx context.Context
//   - plan *commitplan.Plan
func (_e *MockApplier_Expecter) Apply(ctx interface{}, plan interface{}) *MockApplier_Apply_Call {
	return &MockApplier_Apply_Call{Call: _e.mock.On("Apply", ctx, plan)}
}

func (_c *MockApplier_Apply_Call) Run(run func(ctx context.Context, plan *commitplan.Plan)) *MockApplier_Apply_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*commitplan.Plan))
	})
	return _c
}

func (_c *MockApplier_Apply_Call) Return(_a0 error) *MockApplier_Apply_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockApplier_Apply_Call) RunAndReturn(run func(context.Context, *commitplan.Plan) error) *MockApplier_Apply_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockApplier creates a new instance of MockApplier. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockApplier(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockApplier {
	mock := &MockApplier{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
