// Code generated by mockery v2.53.5. DO NOT EDIT.

package commitplan

import (
	context "context"

	commitplan "github.com/dawitel/catalog-proj/internal/commitplan"

	mock "github.com/stretchr/testify/mock"
)

// MockExecutor is an autogenerated mock type for the Executor type
type MockExecutor struct {
	mock.Mock
}

type MockExecutor_Expecter struct {
	mock *mock.Mock
}

func (_m *MockExecutor) EXPECT() *MockExecutor_Expecter {
	return &MockExecutor_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: ctx, plan
func (_m *MockExecutor) Execute(ctx context.Context, plan *commitplan.Plan) error {
	ret := _m.Called(ctx, plan)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *commitplan.Plan) error); ok {
		r0 = rf(ctx, plan)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockExecutor_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockExecutor_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
//   - plan *commitplan.Plan
func (_e *MockExecutor_Expecter) Execute(ctx interface{}, plan interface{}) *MockExecutor_Execute_Call {
	return &MockExecutor_Execute_Call{Call: _e.mock.On("Execute", ctx, plan)}
}

func (_c *MockExecutor_Execute_Call) Run(run func(ctx context.Context, plan *commitplan.Plan)) *MockExecutor_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*commitplan.Plan))
	})
	return _c
}

func (_c *MockExecutor_Execute_Call) Return(_a0 error) *MockExecutor_Execute_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockExecutor_Execute_Call) RunAndReturn(run func(context.Context, *commitplan.Plan) error) *MockExecutor_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockExecutor creates a new instance of MockExecutor. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockExecutor(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockExecutor {
	mock := &MockExecutor{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
